# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_gui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.text = ''

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(190, 70, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 100, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.editingFinished.connect(self.set_line_text)

        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(30, 300, 113, 21))
        self.lineEdit2.setObjectName("lineEdit")
        self.lineEdit2.editingFinished.connect(self.set_line2_text)


        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 200, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("get_text")
        self.pushButton.clicked.connect(self.set_browser_text)

        MainWindow.setCentralWidget(self.centralwidget)

    def set_browser_text(self):
        self.textBrowser.setText(self.text)

    def set_line_text(self):
        self.text += self.lineEdit.text()

    def set_line2_text(self):
        self.text += self.lineEdit2.text()